# Generated by Django 2.2 on 2019-04-22 08:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='prof_pic',
            field=models.ImageField(blank=True, null=True, upload_to='gs://student_profile_pic/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
