# Generated by Django 2.2 on 2019-04-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammates', '0002_auto_20190423_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
