# Generated by Django 2.2 on 2019-05-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammates', '0003_auto_20190423_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='students_rated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='students_reviewed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
