# Generated by Django 2.2 on 2019-05-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammates', '0004_auto_20190501_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='words',
            field=models.TextField(null=True),
        ),
    ]
