# Generated by Django 2.2 on 2019-05-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammates', '0005_student_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
