# [START django_app]
runtime: python37
instance_class: F4_1G
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 2
  max_instances: 20
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50
  max_idle_instances: 2

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
# [END django_app]